# Generated by Django 3.1.7 on 2023-05-02 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20230430_2038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 2, 17, 1, 27, 225717), null=True),
        ),
    ]
