# Generated by Django 3.1.7 on 2023-05-02 16:40

import datetime
from django.db import migrations, models
import store.models.producttype


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20230502_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='alt_image',
            field=models.ImageField(blank=True, upload_to=store.models.producttype.path_and_rename),
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 3, 0, 40, 7, 218161), null=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='image',
            field=models.ImageField(default='image/noimage.jpeg', upload_to=store.models.producttype.path_and_rename),
        ),
    ]
