# Generated by Django 3.1.7 on 2023-05-03 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20230503_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 3, 16, 4, 41, 151640), null=True),
        ),
    ]
