# Generated by Django 3.1.7 on 2023-05-03 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20230503_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='address2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 3, 16, 13, 36, 373943), null=True),
        ),
    ]
